### ISSUE TITLE
Installing a "bundle"

### ISSUE THREAD

**Issue by jpotier** [jwiegley/nix-config#1]
I've just watched "Hom I use nix for Haskell development" on youtube and I find the way you manage bundles of packages very interesting.

I may have missed it from the video, but how do you pull a "bundle" from your `.nixpkgs/config.nix`?

**Comment by jwiegley** [comment]
Can you clarify what you mean by "pulling a bundle"?

**Comment by jpotier** [comment]
I was running `nix-env -iA nixpkgs.musicTools` but met an error telling me this prefix did not exist. And I was very surprised!

I discovered that I had both a `~/.config/nixpkgs/config.nix` and a `~/.nixpkgs/config.nix`, and of course I filled the second one while the first had precedence.

So it has actually nothing to do with your code : )
