### ISSUE TITLE
Question about emacs26

### ISSUE THREAD

**Issue by nasyxx** [jwiegley/nix-config#2]
Hello, I'm new to nix. May I ask a question about emacs26?

I search for how to install emacs 26 with nix, and find one in the overlays folder in this project. Wow, it looks so cool, however, it seems too difficult to me to understand the whole file.

If this doesn't take up too much of your time, could you please tell me what I should do if I want to install emacs26 (I don't need the cocoa version nor the configuration of .emacs.)

**Comment by jwiegley** [comment]
The simplest installation is: `nix-env -i emacs26`.

**Comment by nasyxx** [comment]
Thank you, I have tried it but failed. Do I need to join a particular channel?

```sh
$ nix-env -i emacs26
error: selector 'emacs26' matches no derivations
```

**Comment by jwiegley** [comment]
Oh of course, silly me, Emacs 26 hasn't been released yet.  In my `10-emacs.nix` file I define an expression for that derivation.  But getting that set up in your own environment may require a bit of moving things around.

**Comment by nasyxx** [comment]
It turned out to be this! Anyway, thank you very much. Please let me refer to yours and try to get it done, as my first attempt at nix.
