### ISSUE TITLE
Blog post?

### ISSUE THREAD

**Issue by jhenahan** [jwiegley/nix-config#3]
This is a really fully-featured nix config, and I'd love to build something like it for my own purposes, but it's not altogether clear to me where to get started. Have you written anywhere about how this all came together, or does it fall out naturally as you understand more about Nix? I currently have a fairly basic `nix-darwin` configuration which I use, but finding out more about how you manage Emacs and GHC environments would be really interesting. Even just knowing how you interact with the repo would be helpful. For instance, are files symlinked from the source tree to places that Nix can find them, or do you configure Nix to look for them in your source tree?

Not really an issue, per se, more curiosity at how I can leverage Nix as nicely as you seem to. 😄

**Comment by moritzschaefer** [comment]
A very quick README linking to the install.org would be an easy start

**Comment by toraritte** [comment]
As a blog post or extensive documentation is unlikely to happen (given this is a personal config repo), I would start traversing the commits [from the beginning](https://github.com/jwiegley/nix-config/commits/master?after=657b28262a046f4d9bbf20c0e4a137b9abfa0461+565&branch=master) (there is only the `master` branch), and checking the commit diffs and maybe browsing the repo at that commit if needed. Checked the state at random commits, and complexity is progressing at a welcome pace.
