### ISSUE TITLE
Installation of 'Docker'

### ISSUE THREAD

**Issue by cmacrae** [jwiegley/nix-config#4]
Hey @jwiegley 👋 

Hope you don't mind me opening this issue on your personal config.  
I use nix-darwin for my macOS system configuration and when searching for a means of handling my macOS 'Applications'; I was delighted to find your configuration.  

Using your configuration as reference, I've got a couple applications installed.  
However, I have a particular issue when trying to use the distribution of Docker.  
It seems the "Docker for Mac" implementation runs some scripts at start-up (from clean state) to set up the user's environment. Such as linking binaries to `/usr/local/bin`, etc...

It doesn't seem to want to start. I've had a mix of problems. Initially when it was fresh, it was complaining  it couldn't link  to  `/usr/local/bin`. After a few "resets" it's now just hanging  on  startup  or telling  me it crashed.  

I was wondering  how  you got your Docker  install, as expressed in your `30-apps.nix` configuration  to  work? I assume there are  some manual steps that need to be taken to make  it happy  and start  the daemon?   

Thanks in advance for  any help on  this!

**Comment by jwiegley** [comment]
I bet you I never ran into this because Docker had already been installed at least once.  When I get my new machine next month, you can bet I'll run into this and fix it then. :)

**Comment by cmacrae** [comment]
Ah okay - so I made sure to eradicate every trace of Docker from my system before using a nix expression to install it. Maybe if I re-install it manually, then take it for a spin, it'll work? 🤔 I'll give it a go - if it works, I'll try and work backwards and see if I can hack something together to work from scratch

**Comment by cmacrae** [comment]
Okay, progress so far: I've used `system.activationScripts.postActivation.text` and `system.activationScripts.extraUserActivation.text` from `nix-darwin` to set up some activation scripts to run (can't do this stuff in a `postInstall` as it touches stuff outside the nix-store).

```
  # Set up Docker symlinks
  system.activationScripts.postActivation.text = ''
  declare -a resources=(
               "docker"
               "docker-compose"
               "docker-credential-osxkeychain"
               "docker-machine"
               "notary"
             )

  for resource in "''${resources[@]}" ; do
    ln -sf ${pkgs.Docker}/Applications/Docker.app/Contents/Resources/bin/''${resource} \
      /usr/local/bin/''${resource}
  done

  ln -sf ${pkgs.Docker}/Applications/Docker.app/Contents/Resources/bin/com.docker.hyperkit \
    /usr/local/bin/hyperkit
  ln -sf ${pkgs.Docker}/Applications/Docker.app/Contents/Resources/bin/com.docker.vpnkit \
    /usr/local/bin/vpnkit

  ln -sf ${pkgs.Docker}/Applications/Docker.app/Contents/Library/LaunchServices/com.docker.vmnetd \
    /Library/PrivilegedHelperTools/com.docker.vmnetd

  ln -sf ${pkgs.Docker}/Applications/Docker.app/Contents/Resources/com.docker.vmnetd.plist \
    /Library/LaunchDaemons/com.docker.vmnetd.plist

  launchctl load -Fw /Library/LaunchDaemons/com.docker.vmnetd.plist &> /dev/null
  '';

  system.activationScripts.extraUserActivation.text = "touch /var/tmp/docker.sock";
```

This has gotten it to a state where it's still prompting that privileges be granted on start up so it can set up the environment, however I've whittled it down to these final issues: when starting Docker, you can observe in Console.app that it's upset because of the following:
```
Jul 27 16:59:03 imac com.apple.xpc.launchd[1] (com.apple.xpc.launchd.domain.pid.Docker.9517): Failed to bootstrap path: path = /nix/store/gqh4pycxsb84n01bx87db41xjrsjq21w-Docker-18.03.1-ce-mac65/Applications/Docker.app/Contents/Frameworks/Bugsnag.framework/Versions/A/Bugsnag, error = 20: Not a directory
Jul 27 16:59:03 imac com.apple.xpc.launchd[1] (com.apple.xpc.launchd.domain.pid.Docker.9517): Failed to bootstrap path: path = /nix/store/gqh4pycxsb84n01bx87db41xjrsjq21w-Docker-18.03.1-ce-mac65/Applications/Docker.app/Contents/Frameworks/KeychainAccess.framework/Versions/A/KeychainAccess, error = 20: Not a directory
Jul 27 16:59:03 imac com.apple.xpc.launchd[1] (com.apple.xpc.launchd.domain.pid.Docker.9517): Failed to bootstrap path: path = /nix/store/gqh4pycxsb84n01bx87db41xjrsjq21w-Docker-18.03.1-ce-mac65/Applications/Docker.app/Contents/Frameworks/Sparkle.framework/Versions/A/Sparkle, error = 20: Not a directory
Jul 27 16:59:03 imac com.apple.xpc.launchd[1] (com.apple.xpc.launchd.domain.pid.Docker.9517): Failed to bootstrap path: path = /nix/store/gqh4pycxsb84n01bx87db41xjrsjq21w-Docker-18.03.1-ce-mac65/Applications/Docker.app/Contents/Frameworks/Result.framework/Versions/A/Result, error = 20: Not a directory
Jul 27 16:59:03 imac com.apple.xpc.launchd[1] (com.apple.xpc.launchd.domain.pid.Docker.9517): Failed to bootstrap path: path = /nix/store/gqh4pycxsb84n01bx87db41xjrsjq21w-Docker-18.03.1-ce-mac65/Applications/Docker.app/Contents/Frameworks/EonilFileSystemEvents.framework/Versions/A/EonilFileSystemEvents, error = 20: Not a directory
Jul 27 16:59:03 imac com.apple.xpc.launchd[1] (com.apple.xpc.launchd.domain.pid.Docker.9517): Failed to bootstrap path: path = /nix/store/gqh4pycxsb84n01bx87db41xjrsjq21w-Docker-18.03.1-ce-mac65/Applications/Docker.app/Contents/Frameworks/CwlUtils.framework/Versions/A/CwlUtils, error = 20: Not a directory
```

These messages are indeed correct; those are not directories. They're libraries.  
So I'm not sure what logic the startup of Docker is implementing here, but that's where I've gotten to 🤔

**Comment by jwiegley** [comment]
Hey, that's some nice progress! My only worry is that as this installation complexity increases, the more likely the chance that it will become out of date in the future. Perhaps Docker should just be installed manually on macOS?

**Comment by cmacrae** [comment]
I absolutely agree - there's a lot of stuff that's happening under the hood with this install.  
The steps I've detailed above get it to a state where you can launch Docker installed via the Nix expression, grant it permissions, and it'll work. Whereas before, from a clean state, you'd grant it permissions to do its thing, and it'd crash/hang.  

So it's something, I guess!
If I do manage to get any further with it, I'll let you know, just in case you're interested.  

In any case: thanks for keeping your config public so people can discover awesome stuff like this! 👍
