### ISSUE TITLE
Does this a nix package manager config, or a nix os config?

### ISSUE THREAD

**Issue by cmal** [jwiegley/nix-config#6]
Sorry, I am new to nix. Does this a nix package manager config, or a nix os config? Thanks.

**Comment by jwiegley** [comment]
nix package manager config, and nix-darwin, and home-manager.

**Comment by cmal** [comment]
BTW: If I want to use your nix-config files in my machine, need I use the save version of nix-darwin, and home-manager? Thanks.

**Comment by jwiegley** [comment]
@cmal Hi! It's only known to work with the versions of nix-darwin and home-manager that I refer to; but I update them constantly, so in general it should work with whatever is the latest from those two projects.
